<?php

namespace Mundoreader\CalendarBundle\Entity;

use Doctrine\ORM\EntityRepository;
use DateTime;

/**
 * DayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayRepository extends EntityRepository
{
    /**
     * @param $date DateTime Object
     */
    public function getEventsByMonth($date1, $date2){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $dateFrom = $date1->modify('first day of this month');
        $dateTo = $date2->modify('last day of this month');
        $query = $qb->select('d')
            ->from('Mundoreader\CalendarBundle\Entity\Day', 'd')
            ->andWhere($qb->expr()->between('d.date', ':date_from', ':date_to'))
            ->setParameter('date_from', $dateFrom, \Doctrine\DBAL\Types\Type::DATETIME)
            ->setParameter('date_to', $dateTo, \Doctrine\DBAL\Types\Type::DATETIME)
            ->getQuery();
        $sql = $query->getSQL();
        $days = $query->execute();
        return $days;
    }
}
