<?php

namespace Mundoreader\CalendarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUsersWithoutDay(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM MundoreaderCalendarBundle:User u WHERE u.day is NULL'
            );
    }
}
