<?php

namespace Mundoreader\CalendarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUsersWithoutDay(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM MundoreaderCalendarBundle:User u WHERE u.day is NULL'
            );
    }

    public function clearUserId($user)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $query = $qb->update('Mundoreader\CalendarBundle\Entity\User u')
            ->set('u.day', 'NULL')
            ->andWhere('u.id = :userId')
            ->setParameter('userId', $user->getId())
            ->getQuery();
        $sql = $query->getSQL();
        return $query->execute();
    }
}
