parameters:
#    mundoreader_calendar.example.class: Mundoreader\CalendarBundle\Example

services:
#    mundoreader_calendar.example:
#        class: %mundoreader_calendar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
